[package]
name = "rofd"
version = "0.1.0"
edition = "2021"
description = "An OFD parser and renderer library."
authors = ["HualetWang <hualet@hualet.org>"]
repository = "https://github.com/hualet/rofd"
license = "MIT"

[features]
default = []
qt-reader = ["dep:qmetaobject"]

[dependencies]
cairo-rs = { version = "0.20.7", features = ["png"] }
env_logger = "0.11.6"
log = { version = "0.4.25", features = ["kv"] }
qmetaobject = { version = "0.2.10", optional = true }
serde = { version = "1.0.217", features = ["derive"] }
serde-xml-rs = "0.6.0"
zip = "2.2.2"

[[bin]]
name = "rofd"
path = "src/bin/rofd/main.rs"
required-features = ["qt-reader"]

[workspace]
members = [".", "crates/rofd-core", "crates/rofd-render"]
default-members = ["crates/rofd-core", "crates/rofd-render"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/hualet/rofd"

[workspace.dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde-xml-rs = "0.6.0"
thiserror = "2.0.20"
xml-rs = "0.8.27"
zip = { version = "2.4.2", default-features = false, features = ["deflate"] }
