[package]
name = "rofd"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-rs = { version = "0.20.7", features = ["png"] }
serde = { version = "1.0.217", features = ["derive"] }
serde-xml-rs = "0.6.0"
zip = "2.2.2"
